using System.Net;
using System.Net.Sockets;
using Moongate.Core.Data.Directories;
using Moongate.Core.Types;
using Moongate.Server.Http;
using Moongate.Server.Http.Data;
using Moongate.Tests.TestSupport;

namespace Moongate.Tests.Server.Http;

public class MoongateHttpServiceMetricsEndpointTests
{
    [Test]
    public async Task MetricsEndpoint_WhenFactoryIsConfigured_ShouldReturnPrometheusPayload()
    {
        using var temp = new TempDirectory();
        var directories = new DirectoriesConfig(temp.Path, Enum.GetNames<DirectoryType>());
        var port = GetRandomPort();

        var service = new MoongateHttpService(
            new()
            {
                DirectoriesConfig = directories,
                Port = port,
                IsOpenApiEnabled = false,
                MetricsSnapshotFactory = () =>
                                             new()
                                             {
                                                 CollectedAt = DateTimeOffset.FromUnixTimeMilliseconds(1735689600000),
                                                 Metrics = new Dictionary<string, MoongateHttpMetric>(StringComparer.Ordinal)
                                                 {
                                                     ["test.ticks.total"] = new()
                                                     {
                                                         Name = "ticks.total",
                                                         Value = 12
                                                     }
                                                 }
                                             }
            }
        );

        await service.StartAsync();

        try
        {
            using var http = new HttpClient();
            var response = await http.GetAsync($"http://127.0.0.1:{port}/metrics");
            var body = await response.Content.ReadAsStringAsync();

            Assert.Multiple(
                () =>
                {
                    Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
                    Assert.That(body, Does.Contain("# generated by moongate"));
                    Assert.That(body, Does.Contain("collected_at_unix_ms 1735689600000"));
                    Assert.That(body, Does.Contain("moongate_test_ticks_total 12"));
                }
            );
        }
        finally
        {
            await service.StopAsync();
        }
    }

    [Test]
    public async Task MetricsEndpoint_WhenFactoryIsMissing_ShouldReturnNotFound()
    {
        using var temp = new TempDirectory();
        var directories = new DirectoriesConfig(temp.Path, Enum.GetNames<DirectoryType>());
        var port = GetRandomPort();

        var service = new MoongateHttpService(
            new()
            {
                DirectoriesConfig = directories,
                Port = port,
                IsOpenApiEnabled = false
            }
        );

        await service.StartAsync();

        try
        {
            using var http = new HttpClient();
            var response = await http.GetAsync($"http://127.0.0.1:{port}/metrics");
            var body = await response.Content.ReadAsStringAsync();

            Assert.Multiple(
                () =>
                {
                    Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
                    Assert.That(body, Is.EqualTo("metrics endpoint is not configured"));
                }
            );
        }
        finally
        {
            await service.StopAsync();
        }
    }

    private static int GetRandomPort()
    {
        using var listener = new TcpListener(IPAddress.Loopback, 0);
        listener.Start();
        var endpoint = (IPEndPoint)listener.LocalEndpoint;

        return endpoint.Port;
    }
}
